gestion_proceso:
    resource: "@GestionBundle/Controller/ProcesoController.php"
    type:     annotation

gestion_estado_atencion:
    resource: "@GestionBundle/Controller/EstadoAtencionController.php"
    type:     annotation

gestion_contacto:
    resource: "@GestionBundle/Controller/ContactoController.php"
    type:     annotation

gestion_cliente:
    resource: "@GestionBundle/Controller/ClienteController.php"
    type:     annotation

gestion_cliente_contacto:
    resource: "@GestionBundle/Controller/ClienteContactoController.php"
    type:     annotation

gestion_atencion:
    resource: "@GestionBundle/Controller/AtencionController.php"
    type:     annotation

gestion_atencion_detalle:
    resource: "@GestionBundle/Controller/AtencionDetalleController.php"
    type:     annotation

gestion_area:
    resource: "@GestionBundle/Controller/AreaController.php"
    type:     annotation

gestion_archivo:
    resource: "@GestionBundle/Controller/ArchivoController.php"
    type:     annotation

administracion_usuario:
    resource: "@AdministracionBundle/Controller/UsuarioController.php"
    type:     annotation

administracion_usuario_sucursal:
    resource: "@AdministracionBundle/Controller/UsuarioSucursalController.php"
    type:     annotation

administracion_tipo_contacto:
    resource: "@AdministracionBundle/Controller/TipoContactoController.php"
    type:     annotation

administracion_sucursal:
    resource: "@AdministracionBundle/Controller/SucursalController.php"
    type:     annotation

administracion_rol:
    resource: "@AdministracionBundle/Controller/RolController.php"
    type:     annotation

administracion_empresa:
    resource: "@AdministracionBundle/Controller/EmpresaController.php"
    type:     annotation

administracion_empleado:
    resource: "@AdministracionBundle/Controller/EmpleadoController.php"
    type:     annotation

administracion_contacto:
    resource: "@AdministracionBundle/Controller/ContactoController.php"
    type:     annotation

gestion:
    resource: "@GestionBundle/Controller/"
    type:     annotation
    prefix:   /gestion

administracion:
    resource: "@AdministracionBundle/Controller/"
    type:     annotation
    prefix:   /users

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /users/logout